import path from 'path';
import dotenv from 'dotenv';
import { defineConfig, devices } from '@playwright/test';
import { getEnvConfig } from './config/qa.env';

dotenv.config({ path: path.resolve(__dirname, '.env'), override: true });

const envConfig = getEnvConfig();

export default defineConfig({
  /* Test directory */
  testDir: './tests',

  /* Run tests in files in parallel */
  fullyParallel: false,

  /* Fail the build on CI if you accidentally left test.only in the source code */
  forbidOnly: !!process.env.CI,

  /* Retry on CI only */
  retries: process.env.CI ? 2 : 1,

  /* Workers — limit parallelism for AP workflows */
  workers: process.env.CI ? 1 : 2,

  /* Reporter configuration */
  reporter: [
    ['html', { outputFolder: 'reports/html-report', open: 'never' }],
    ['list'],
    ['allure-playwright', { resultsDir: 'reports/allure-results' }],
  ],

  /* Global setup */
  globalSetup: './hooks/globalSetup.ts',

  /* Shared settings for all projects */
  use: {
    /* Visible browser locally; headless on CI */
    headless: !!process.env.CI,

    /* Base URL for navigation */
    baseURL: envConfig.baseURL,

    /* Reuse authenticated browser state generated by global setup */
    storageState: 'playwright/.auth/user.json',

    /* Collect trace on first retry */
    trace: 'on-first-retry',

    /* Use custom fixture-based screenshot handling in screenshots/<testcase> */
    screenshot: 'off',

    /* Video recording */
    video: 'retain-on-failure',

    /* Timeouts */
    actionTimeout: 30_000,
    navigationTimeout: 60_000,

    /* Viewport */
    viewport: { width: 1920, height: 1080 },

    /* Ignore HTTPS errors */
    ignoreHTTPSErrors: true,
  },

  /* Global test timeout */
  timeout: 120_000,

  /* Expect timeout */
  expect: {
    timeout: 15_000,
  },

  /* Output directory for test artifacts */
  outputDir: './test-results',

  /* Projects / browser configurations */
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        launchOptions: {
          args: ['--start-maximized'],
        },
      },
    },
    // Uncomment to add more browsers:
    // {
    //   name: 'firefox',
    //   use: { ...devices['Desktop Firefox'] },
    // },
    // {
    //   name: 'webkit',
    //   use: { ...devices['Desktop Safari'] },
    // },
  ],
});
